format = """
$username\
$hostname\
[î‚°](bg:#769ff0 fg:#000000)\
$directory\
[î‚°](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚°](fg:#394260 bg:#212736)\
$python\
$nodejs\
$rust\
$golang\
$php\
[î‚° ](fg:#1d2230)\
\nâ•°â”€>$character"""

add_newline = false

[directory]
style = "fg:black bg:#769ff0"
format = "[ $path ]($style)"
truncate_to_repo = true
truncation_length = 10
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"downloads" = "ï€™ "
"Music" = "ï€ "
"music" = "ï€ "
"Pictures" = "ï€¾ "
"pictures" = "ï€¾ "

[username]
show_always = true
style_user = "bg:#000000 fg:white"
format = "[ $user]($style)"

[hostname]
ssh_only = false
style = "bg:#000000 fg:white"
format = "[@$hostname ]($style)"

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
conflicted = 'ğŸ³'
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â‡•'
up_to_date = ''
untracked = '?'
stashed = 'ğŸ“¦'
modified = '!'
staged = '[++\($count\)](fg:#769ff0 bg:#394260)'
renamed = 'ğŸ‘…'
deleted = 'âœ˜'

[python]
style = "bg:#212736"
format = "[ $symbol(venv:$virtualenv)]($style)"

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

